version: "3.8"

services:
  db:
    image: postgres:16
    container_name: ovs-postgres
    restart: always
    environment:
      POSTGRES_USER: ovs
      POSTGRES_PASSWORD: ovs
      POSTGRES_DB: ovs
    ports:
      - "5432:5432"
    volumes:
      - ovs_pg:/var/lib/postgresql/data

volumes:
  ovs_pg:
