spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

logging:
    level:
        "[org.springframework.security]": INFO

app:
    tally:
        python: ${APP_TALLY_PYTHON:python}
        script: ${APP_TALLY_SCRIPT:./scripts/generate_chart.py}
        workDir: ${APP_TALLY_WORKDIR:.}
        jsonDir: ${APP_TALLY_JSONDIR:./data/tally}
        chartDir: ${APP_TALLY_CHARTDIR:./data/charts}
